config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get '/check', to: proc {[200, {}, ['it_works']]}
  # Sidekiq web config
  scope :monitoring do
    mount Sidekiq::Web => '/sidekiq'
    Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
      [user, password] == [ENV['SIDEKIQ_USERNAME'], ENV['SIDEKIQ_PASSWORD']]
    end
    Sidekiq::Web.set(:session_secret, Rails.application.secrets[:secret_key_base])
  end

  get 'dashboard', to: 'dashboards#dashboard'
  root to: 'dashboards#dashboard'

  # Dashboard charts
  resources :charts do
    collection do
      get 'chart_families'
      get 'chart_family_members'
      get 'chart_home_visit_registrations'
      get 'chart_home_registrations'
      get 'chart_individual_registrations'
      get 'chart_periods'
      get 'chart_vaccinations'
    end
  end

  resources :generic_models do
    collection do
      get 'address_types'
      get 'cbo_types'
      get 'ethnicity_types'
      get 'carried_procedures'
      get 'exams'
      get 'pharmaceutical_forms'
      get 'duration_types'
      get 'dose_frequency_types'
      get 'administration_ways'
      get 'recipe_types'
      get 'specialties'
    end
  end

  resources :states
  resources :cities
  resources :families
  resources :companies do
    collection do
      post 'change_company'
    end
  end
  resources :appointment_demands
  resources :appointment_bookings
  resources :family_members do
    resources :patient_records
  end
  resources :home_registrations
  resources :professional_teams
  resources :health_professionals
  resources :health_establishments
  resources :home_visit_forms
  resources :home_visit_registrations
  resources :individual_registrations
  resources :vaccinations
  resources :vaccination_campaigns do
    member do
      get 'update_map'
    end
  end
  resources :roles
  resources :sms_messages
  resources :sms_schedules do
    member do
      post 'send_sms_messages'
    end
  end
  resources :medicines
  resources :vaccines
  resources :periods
  resources :period_items, only: %i[index show]
  resources :reports, only: [] do
    collection do
      get 'vaccinations'
      get 'home_registrations'
      get 'home_visit_registrations'
      get 'families'
      get 'family_members'
      get 'vaccination_campaigns'
      get 'individual_registrations'
      get 'resume_registry'
      get 'sociodemographic_situation'
      get 'street_situation'
      get 'family_member_disabilities'
    end
  end

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
  }, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }

  devise_scope :user do
    resources :users
  end

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth', controllers: {
      sessions: 'api/overrides/sessions',
    }

    resources :states
    resources :cities
    resources :families
    resources :family_members

    # Home Registrations
    resources :home_registrations, except: %i[new edit]
    resources :living_conditions, except: %i[index new edit]
    resources :addresses, except: %i[index new edit]

    # Professional Teams
    resources :professional_teams, except: %i[new edit] do
      shallow do
        resources :health_professionals, except: %i[new edit] do
          shallow do
            resources :home_registrations, only: %i[index]
          end
        end
      end
    end

    # Home Visit Registrations
    resources :home_visit_registrations
    resources :home_visit_forms

    # States & Cities
    resources :states, only: %i[index show] do
      shallow do
        resources :cities, only: %i[index show]
      end
    end

    # Individual Registrations
    resources :individual_registrations, except: %i[new edit]
    resources :health_conditions, except: %i[index new edit]
    resources :living_conditions, except: %i[index new edit]
    resources :in_street_situations, except: %i[index new edit]
    resources :sociodemographic_infos, except: %i[index new edit]
    resources :cancel_registrations, except: %i[index new edit]

    # Health Establishments
    resources :health_establishments, except: %i[index new edit] do
      shallow do
        resources :health_professionals, only: %i[index show]
      end
    end

    # Generic Models
    resources :generic_models, only: :types do
     collection do
       get 'types'
     end
    end
  end
end

app/models/appointment_booking.rb
# frozen_string_literal: true
class AppointmentBooking < ApplicationRecord
  include Sluggable
  include Tenantable

  has_rich_text :observation

  belongs_to :health_professional
  belongs_to :family_member, class_name: 'FamilyMember'
  belongs_to :medical_procedure, class_name: 'GenericModel'
  belongs_to :company

  has_one :patient_record

  validates :appointment_date, :start_hour, :end_hour, :observation, presence: true

  accepts_nested_attributes_for :family_member, allow_destroy: false

  ransack_alias :search, :id_to_s
end

app/controllers/appointment_bookings_controller.rb
# frozen_string_literal: true
class AppointmentBookingsController < WebController
  before_action :set_appointment_booking, only: %i[show edit update destroy]

  breadcrumb AppointmentBooking.model_name.human(count: 2), :appointment_bookings_path

  # GET /appointment_bookings
  def index
    authorize(AppointmentBooking)
    @query = AppointmentBooking.ransack(params[:q])
    @result = @query.result
    if current_user.doctor?
      @result = @result.includes(:health_professional)
                    .where(health_professional: HealthProfessional.find_by(user: current_user))
    end
    @pagy, @appointment_bookings = pagy(@result.includes(:family_member,
                                                         :medical_procedure, :health_professional), page: params[:page], items: 10)
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /appointment_bookings/1
  def show
    authorize(@appointment_booking)
    breadcrumb(@appointment_booking.slug, appointment_booking_path)
    @family_member_selected = @appointment_booking.family_member.presence
  end

  # GET /appointment_bookings/new
  def new
    authorize(AppointmentBooking)
    breadcrumb(t('helpers.submit.new'), new_appointment_booking_path)
    @appointment_booking = AppointmentBooking.new
  end

  # GET /appointment_bookings/1/edit
  def edit
    authorize(@appointment_booking)
    breadcrumb(@appointment_booking.slug, appointment_booking_path(@appointment_booking))
  end

  # POST /appointment_bookings
  def create
    authorize(AppointmentBooking)
    breadcrumb(t('helpers.submit.new'), new_appointment_booking_path)
    @appointment_booking = AppointmentBooking.new(appointment_booking_params)
    @family_member_selected = @appointment_booking.family_member.presence

    if @appointment_booking.save
      redirect_to(@appointment_booking, notice: 'Appointment booking was successfully created.')
    else
      render(:new)
    end
  end

  # PATCH/PUT /appointment_bookings/1
  def update
    authorize(AppointmentBooking)
    breadcrumb(@appointment_booking.slug, appointment_booking_path(@appointment_booking))
    if @appointment_booking.update(appointment_booking_params)
      redirect_to(@appointment_booking, notice: 'Appointment booking was successfully updated.')
    else
      render(:edit)
    end
  end

  # DELETE /appointment_bookings/1
  def destroy
    authorize(AppointmentBooking)
    @appointment_booking.destroy
    redirect_to(appointment_bookings_url, notice: 'Appointment booking was successfully destroyed.')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_appointment_booking
    @appointment_booking = AppointmentBooking.friendly.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def appointment_booking_params
    params.require(:appointment_booking).permit(:health_professional_id, :family_member_id,
                                                :appointment_date, :start_hour, :end_hour, :observation,
                                                :priority,
                                                :phone, :medical_procedure_id)
  end
end

app/views/appointment_bookings/_form.html.erb
<%= simple_form_for(@appointment_booking) do |f| %>
  <% content_for :body do %>
    <%= f.association :health_professional, collection: HealthProfessional.only_doctors, label_method: :name_formatted,
                      wrapper_html: {class: 'col-lg-6 col-sm-12'}, input_html: {class: 'select2', disabled: show?(f.object.persisted?)} %>
    <%= f.association :family_member,
                      collection: @family_member_selected ? [@family_member_selected] : [],
                      selected: @family_member_selected,
                      label_method: :name_formatted,
                      wrapper_html: {class: 'col-lg-6 col-sm-12'}, input_html: {class: 'family-members', disabled: show?(f.object.persisted?)} %>
    <%= f.input :appointment_date, html5: true, wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.input :start_hour, html5: true, wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.input :end_hour, html5: true, wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.input :status, wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.input :priority, as: :select, collection: [[t('simple_form.yes'), 1], [t('simple_form.no'), 0]], wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {class: 'select2', disabled: show?(f.object.persisted?)} %>
    <%= f.input :phone, wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.association :medical_procedure, collection: GenericModel.medical_procedures,
                      wrapper_html: {class: 'col-lg-12 col-sm-12'}, input_html: {class: 'select2', disabled: show?(f.object.persisted?)} %>
    <div class="col-lg-12">
      <% if show?(f.object.persisted?) %>
        <%= f.label :observation, class: 'form-label' %>
        <div class="form-control">
          <%= @appointment_booking.observation.to_plain_text %>
        </div>
      <% else %>
        <%= f.rich_text_area :observation, disabled: show?(f.object.persisted?) %>
      <% end %>
    </div>
  <% end %>
  <%= render template: 'application/form', locals: {form: @appointment_booking, other_url: dashboard_path} %>
<% end %>

app/views/appointment_bookings/edit.html.erb
<%= render 'form', form: @appointment_booking %>

app/views/appointment_bookings/index.html.erb
<%= render 'application/page_header', model: AppointmentBooking %>
<div class="card">
  <div class="card-status bg-transparent"></div>
  <div class="card-header p-4">
    <div class="col-sm-12 col-lg-12">
      <div class="form-row">
        <div class="col-sm-12 col-lg-6 p-0">
          <%= render 'application/pagy_count', list: @pagy, model: AppointmentBooking, url: new_appointment_booking_path %>
        </div>
        <div class="col-sm-12 col-lg-6 p-0">
          <%= search_form_for @query do |f| %>
            <%= f.search_field :search_cont, class: 'form-control', placeholder: t('helpers.search') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body table-responsive p-0 m-0">
    <table class="table card-table table-vcenter text-nowrap table-hover">
      <thead>
      <tr>
        <th><%= AppointmentBooking.human_attribute_name :health_professional %></th>
        <th><%= AppointmentBooking.human_attribute_name :family_member %></th>
        <th><%= AppointmentBooking.human_attribute_name :appointment_date %></th>
        <th><%= AppointmentBooking.human_attribute_name :start_hour %></th>
        <th><%= AppointmentBooking.human_attribute_name :end_hour %></th>
        <th><%= AppointmentBooking.human_attribute_name :medical_procedure %></th>
        <th><%= t('helpers.actions.action') %></th>
      </tr>
      </thead>
      <tbody>
      <% @appointment_bookings.each do |appointment_booking| %>
        <tr>
          <td><%= appointment_booking.health_professional.full_name %></td>
          <td><%= appointment_booking.family_member.name %></td>
          <td><%= appointment_booking.appointment_date&.strftime('%d/%m/%Y') %></td>
          <td><%= appointment_booking.start_hour&.strftime('%H:%M') %></td>
          <td><%= appointment_booking.end_hour&.strftime('%H:%M') %></td>
          <td><%= appointment_booking.medical_procedure.name %></td>
          <td class="text-center">
            <%= render 'application/table_links', f: appointment_booking %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <%= render 'application/footer_links', url: new_appointment_booking_path, model: AppointmentBooking %>
  </div>
</div>

app/views/appointment_bookings/index.js.erb
$('#appointment-bookings').html("<%= j render 'application/appointment_bookings' %>");

app/views/appointment_bookings/new.html.erb
<%= render 'form', form: @appointment_booking %>

app/views/appointment_bookings/show.html.erb
<%= render 'form', form: @appointment_booking %>