config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get '/check', to: proc {[200, {}, ['it_works']]}
  # Sidekiq web config
  scope :monitoring do
    mount Sidekiq::Web => '/sidekiq'
    Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
      [user, password] == [ENV['SIDEKIQ_USERNAME'], ENV['SIDEKIQ_PASSWORD']]
    end
    Sidekiq::Web.set(:session_secret, Rails.application.secrets[:secret_key_base])
  end

  get 'dashboard', to: 'dashboards#dashboard'
  root to: 'dashboards#dashboard'

  # Dashboard charts
  resources :charts do
    collection do
      get 'chart_families'
      get 'chart_family_members'
      get 'chart_home_visit_registrations'
      get 'chart_home_registrations'
      get 'chart_individual_registrations'
      get 'chart_periods'
      get 'chart_vaccinations'
    end
  end

  resources :generic_models do
    collection do
      get 'address_types'
      get 'cbo_types'
      get 'ethnicity_types'
      get 'carried_procedures'
      get 'exams'
      get 'pharmaceutical_forms'
      get 'duration_types'
      get 'dose_frequency_types'
      get 'administration_ways'
      get 'recipe_types'
      get 'specialties'
    end
  end

  resources :states
  resources :cities
  resources :families
  resources :companies do
    collection do
      post 'change_company'
    end
  end
  resources :appointment_demands
  resources :appointment_bookings
  resources :family_members do
    resources :patient_records
  end
  resources :home_registrations
  resources :professional_teams
  resources :health_professionals
  resources :health_establishments
  resources :home_visit_forms
  resources :home_visit_registrations
  resources :individual_registrations
  resources :vaccinations
  resources :vaccination_campaigns do
    member do
      get 'update_map'
    end
  end
  resources :roles
  resources :sms_messages
  resources :sms_schedules do
    member do
      post 'send_sms_messages'
    end
  end
  resources :medicines
  resources :vaccines
  resources :periods
  resources :period_items, only: %i[index show]
  resources :reports, only: [] do
    collection do
      get 'vaccinations'
      get 'home_registrations'
      get 'home_visit_registrations'
      get 'families'
      get 'family_members'
      get 'vaccination_campaigns'
      get 'individual_registrations'
      get 'resume_registry'
      get 'sociodemographic_situation'
      get 'street_situation'
      get 'family_member_disabilities'
    end
  end

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
  }, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }

  devise_scope :user do
    resources :users
  end

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth', controllers: {
      sessions: 'api/overrides/sessions',
    }

    resources :states
    resources :cities
    resources :families
    resources :family_members

    # Home Registrations
    resources :home_registrations, except: %i[new edit]
    resources :living_conditions, except: %i[index new edit]
    resources :addresses, except: %i[index new edit]

    # Professional Teams
    resources :professional_teams, except: %i[new edit] do
      shallow do
        resources :health_professionals, except: %i[new edit] do
          shallow do
            resources :home_registrations, only: %i[index]
          end
        end
      end
    end

    # Home Visit Registrations
    resources :home_visit_registrations
    resources :home_visit_forms

    # States & Cities
    resources :states, only: %i[index show] do
      shallow do
        resources :cities, only: %i[index show]
      end
    end

    # Individual Registrations
    resources :individual_registrations, except: %i[new edit]
    resources :health_conditions, except: %i[index new edit]
    resources :living_conditions, except: %i[index new edit]
    resources :in_street_situations, except: %i[index new edit]
    resources :sociodemographic_infos, except: %i[index new edit]
    resources :cancel_registrations, except: %i[index new edit]

    # Health Establishments
    resources :health_establishments, except: %i[index new edit] do
      shallow do
        resources :health_professionals, only: %i[index show]
      end
    end

    # Generic Models
    resources :generic_models, only: :types do
     collection do
       get 'types'
     end
    end
  end
end

app/models/generic_model.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: generic_models
#
#  id               :bigint           not null, primary key
#  description      :string
#  generic_class    :string
#  generic_field    :string
#  name             :string
#  reference        :string
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  generic_model_id :bigint
#
# Indexes
#
#  index_generic_models_on_generic_model_id  (generic_model_id)
#
# Foreign Keys
#
#  fk_rails_...  (generic_model_id => generic_models.id)
#

class GenericModel < ApplicationRecord
  include Sluggable

  belongs_to :generic_model, optional: true

  ransack_alias :search, :id_to_s_or_name_or_reference

  scope :app_modules, -> { where(generic_field: :app_module) }
  scope :nationalities, -> { where(generic_field: :nationality) }
  scope :races, -> { where(generic_field: :race) }
  scope :genders, -> { where(generic_field: :gender) }
  scope :gender_identities, -> { where(generic_field: :gender_identity) }
  scope :ethnicities, -> { where(generic_field: :ethnicity) }
  scope :countries, -> { where(generic_field: :country) }
  scope :address_types, -> { where(generic_field: :address_type) }
  scope :water_supplies, -> { where(generic_field: :water_supply) }
  scope :rural_production_areas, -> { where(generic_field: :rural_production_area) }
  scope :garbage_disposals, -> { where(generic_field: :garbage_disposal) }
  scope :bathroom_drainage, -> { where(generic_field: :bathroom_drainage) }
  scope :home_wall_materials, -> { where(generic_field: :home_wall_material) }
  scope :home_locations, -> { where(generic_field: :home_location) }
  scope :home_situations, -> { where(generic_field: :home_situation) }
  scope :hygiene_access, -> { where(generic_field: :hygiene_access) }
  scope :home_accesses, -> { where(generic_field: :home_access) }
  scope :home_types, -> { where(generic_field: :home_type) }
  scope :residence_types, -> { where(generic_field: :residence_type) }
  scope :water_treatments, -> { where(generic_field: :water_treatment) }
  scope :pet_types, -> { where(generic_field: :pet_type) }
  scope :unit_types, -> { where(generic_field: :unit_type) }
  scope :cbo_types, -> { where(generic_field: :cbo_type) }
  scope :breastfeeding, -> { where(generic_field: :breastfeeding) }
  scope :weight_situations, -> { where(generic_field: :weight_situation_type) }
  scope :meals_per_day, -> { where(generic_field: :meals_quantity_type) }
  scope :street_situation_time, -> { where(generic_field: :street_situation_time) }
  scope :meals_origin_types, -> { where(generic_field: :meals_origin_type) }
  scope :respiratory_diseases, -> { where(generic_field: :respiratory_disease) }
  scope :kidney_problems, -> { where(generic_field: :kidney_problem) }
  scope :heart_diseases, -> { where(generic_field: :heart_disease) }
  scope :turns, -> { where(generic_field: :turn) }
  scope :outcomes, -> { where(generic_field: :outcome) }
  scope :visit_reasons, -> { where(generic_field: :reason) }
  scope :sexual_orientations, -> { where(generic_field: :sexual_orientation) }
  scope :education_levels, -> { where(generic_field: :education_level) }
  scope :parent_relations, -> { where(generic_field: :parent_relation) }
  scope :job_market_situations, -> { where(generic_field: :job_market_situation) }
  scope :child_responsible, -> { where(generic_field: :child_responsible) }
  scope :left_reasons, -> { where(generic_field: :left_reason) }
  scope :family_incomes, -> { where(generic_field: :family_income) }
  scope :local_services, -> { where(generic_field: :local_service) }
  scope :immunobiological, -> { where(generic_field: :immunobiological) }
  scope :vaccination_strategies, -> { where(generic_field: :vaccination_strategy) }
  scope :doses, -> { where(generic_field: :dose) }
  scope :disabilities, -> { where(generic_field: :citizen_disability) }
  scope :therapeutic_classes, -> { where(generic_field: :therapeutic_class) }
  scope :product_types, -> { where(generic_field: :product_type) }
  scope :stripes, -> { where(generic_field: :stripe) }
  scope :medical_procedures, -> { where(generic_field: :medical_procedure) }
  scope :collected_times, -> { where(generic_field: :collected_time) }
  scope :demand_types, -> { where(generic_field: :demand_type) }
  scope :carried_procedures, -> { where(generic_field: :carried_procedure) }
  scope :exams, -> { where(generic_field: :exam) }
  scope :pharmaceutical_forms, -> { where(generic_field: :pharmaceutical_form) }
  scope :specialties, -> { where(generic_field: :specialty) }
  scope :by_module_reference, ->(reference) { app_modules.find_by(reference: reference) }

  def name_formatted
    return name.mb_chars.upcase if reference.blank?

    "#{reference} - #{name.mb_chars.upcase}"
  end
end

app/controllers/api/generic_models_controller.rb
# frozen_string_literal: true

module Api
  class GenericModelsController < Api::ApiController
    skip_before_action :authenticate_user!
    before_action :set_query, except: %i[types cbo_types ethnicity_types]

    def types
      authorize(GenericModel, :types, policy_class: Api::GenericModelPolicy )
      generic_models = Rails.cache.fetch('generic_models') do
        GenericModel.all
          .select(:id, :name, :reference, :generic_field)
          .group_by(&:generic_field)
      end
      render(json: generic_models, adapter: false)
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_generic_model
      @generic_model = GenericModel.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def generic_model_params
      params.require(:generic_model).permit(:name, :description, :reference,
                                            :generic_field, :generic_class,
                                            :generic_model_id)
    end
  end
end

app/controllers/generic_models_controller.rb
# frozen_string_literal: true

class GenericModelsController < WebController
  before_action :set_generic_model, only: %i[show edit update destroy]
  before_action :set_query, except: %i[index new create show edit update destroy]

  # GET /generic_models
  def index
    authorize(GenericModel)
    @query = GenericModel.ransack(params[:q])
    @pagy, @generic_models = pagy(@query.result, page: params[:page], items: 10)
  end

  def address_types
    authorize(GenericModel)
    render_json(@result.address_types)
  end

  def cbo_types
    authorize(GenericModel)
    render_json(@result.cbo_types)
  end

  def ethnicity_types
    authorize(GenericModel)
    render_json(@result.ethnicities)
  end

  def carried_procedures
    authorize(GenericModel)
    render_json(@result.carried_procedures)
  end

  def exams
    authorize(GenericModel)
    render_json(@result.exams)
  end

  def pharmaceutical_forms
    authorize(GenericModel)
    render_json(@result.pharmaceutical_forms)
  end

  def collected_times
    authorize(GenericModel)
    render_json(@result.collected_times)
  end

  def duration_types
    authorize(GenericModel)
    render_json(@result.duration_types)
  end

  def dose_frequency_types
    authorize(GenericModel)
    render_json(@result.dose_frequency_types)
  end

  def specialties
    authorize(GenericModel)
    render_json(@result.specialties)
  end

  # GET /generic_models/1
  def show
    authorize(@generic_model)
  end

  # GET /generic_models/new
  def new
    authorize(@generic_model)
    @generic_model = GenericModel.new
  end

  # GET /generic_models/1/edit
  def edit
    authorize(@generic_model)
  end

  # POST /generic_models
  def create
    authorize(GenericModel)
    @generic_model = GenericModel.new(generic_model_params)

    if @generic_model.save
      redirect_to(@generic_model, notice: 'Generic model was successfully created.')
    else
      render(:new)
    end
  end

  # PATCH/PUT /generic_models/1
  def update
    authorize(@generic_model)
    if @generic_model.update(generic_model_params)
      redirect_to(@generic_model, notice: 'Generic model was successfully updated.')
    else
      render(:edit)
    end
  end

  # DELETE /generic_models/1
  def destroy
    authorize(@generic_model)
    @generic_model.destroy
    redirect_to(generic_models_url, notice: 'Generic model was successfully destroyed.')
  end

  private

  def set_query
    @query = GenericModel.ransack(params[:q])
    @result = @query.result.includes(:generic_model)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_generic_model
    @generic_model = GenericModel.friendly.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def generic_model_params
    params.require(:generic_model).permit(:name, :description, :reference,
                                          :generic_field, :generic_class,
                                          :generic_model_id)
  end
end

app/views/generic_models/_form.html.erb
<%= form_with(model: @generic_model, id: :generic_model) do |f| %>
  <% content_for :body do %>
    <div class="form-group col-md-4">
      <%= f.label :name, {class: 'form-label'} %>
      <%= f.text_field :name, {class: 'form-control', disabled: show?(f.object.persisted?)} %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :description, {class: 'form-label'} %>
      <%= f.text_field :description, {class: 'form-control', disabled: show?(f.object.persisted?)} %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :reference, {class: 'form-label'} %>
      <%= f.text_field :reference, {class: 'form-control', disabled: show?(f.object.persisted?)} %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :generic_field, {class: 'form-label'} %>
      <%= f.text_field :generic_field, {class: 'form-control', disabled: show?(f.object.persisted?)} %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :generic_class, {class: 'form-label'} %>
      <%= f.text_field :generic_class, {class: 'form-control', disabled: show?(f.object.persisted?)} %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :generic_model_id, {class: 'form-label'} %>
      <%= f.select :generic_model_id, options_from_collection_for_select([], :name, :id),
                   {include_blank: 'Selecione'}, {class: 'form-control', disabled: show?(f.object.persisted?)} %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :slug, {class: 'form-label'} %>
      <%= f.text_field :slug, {class: 'form-control', disabled: show?(f.object.persisted?)} %>
    </div>
  <% end %>
  <%= render template: 'application/form', locals: {form: @generic_model} %>
<% end %>

app/views/generic_models/edit.html.erb
<%= render 'form', form: @generic_model %>

app/views/generic_models/index.html.erb
<%= render 'application/page_header', model: GenericModel %>
<div class="card">
  <div class="card-status bg-transparent"></div>
  <div class="card-header p-4">
    <div class="col-sm-12 col-lg-12">
      <div class="form-row">
        <div class="col-sm-12 col-lg-6 p-0">
          <%= render 'application/pagy_count', list: @pagy, model: GenericModel, url: new_generic_model_path %>
        </div>
        <div class="col-sm-12 col-lg-6 p-0">
          <%= search_form_for @query do |f| %>
            <%= f.search_field :search_cont, class: 'form-control', placeholder: t('helpers.search') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body table-responsive p-0 m-0">
    <table class="table card-table table-vcenter text-nowrap table-hover">
      <thead>
      <tr>
        <th><%= GenericModel.human_attribute_name :name %></th>
        <th><%= GenericModel.human_attribute_name :description %></th>
        <th><%= GenericModel.human_attribute_name :reference %></th>
        <th><%= GenericModel.human_attribute_name :generic_field %></th>
        <th><%= GenericModel.human_attribute_name :generic_class %></th>
        <th><%= GenericModel.human_attribute_name :generic_model %></th>
        <th><%= GenericModel.human_attribute_name :slug %></th>
        <% if policy(GenericModel).show? %>
          <th><%= t('helpers.actions.action') %></th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% @generic_models.each do |generic_model| %>
        <tr>
          <td><%= generic_model.name %></td>
          <td><%= generic_model.description %></td>
          <td><%= generic_model.reference %></td>
          <td><%= generic_model.generic_field %></td>
          <td><%= generic_model.generic_class %></td>
          <td><%= generic_model.generic_model_id %></td>
          <td><%= generic_model.slug %></td>
          <% if policy(GenericModel).show? %>
            <td>
              <%= render 'application/table_links', f: generic_model %>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <div class="col-12">
      <div class="row">
        <div class="col-sm-12 col-lg-6 p-0">
          <%= link_to new_generic_model_path, class: 'btn btn-primary align-middle mb-md-0 mb-sm-3' do %>
            <i class="fas fa-plus mr-2"></i>Novo
          <% end %>
        </div>
        <div class="col-sm-12 col-lg-6 p-0">
          <div class="float-right">
            <%= pagy_bootstrap_nav(@pagy).html_safe %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/generic_models/new.html.erb
<%= render 'form', form: @generic_model %>

app/views/generic_models/show.html.erb
<%= render 'form', form: @generic_model %>