config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get '/check', to: proc {[200, {}, ['it_works']]}
  # Sidekiq web config
  scope :monitoring do
    mount Sidekiq::Web => '/sidekiq'
    Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
      [user, password] == [ENV['SIDEKIQ_USERNAME'], ENV['SIDEKIQ_PASSWORD']]
    end
    Sidekiq::Web.set(:session_secret, Rails.application.secrets[:secret_key_base])
  end

  get 'dashboard', to: 'dashboards#dashboard'
  root to: 'dashboards#dashboard'

  # Dashboard charts
  resources :charts do
    collection do
      get 'chart_families'
      get 'chart_family_members'
      get 'chart_home_visit_registrations'
      get 'chart_home_registrations'
      get 'chart_individual_registrations'
      get 'chart_periods'
      get 'chart_vaccinations'
    end
  end

  resources :generic_models do
    collection do
      get 'address_types'
      get 'cbo_types'
      get 'ethnicity_types'
      get 'carried_procedures'
      get 'exams'
      get 'pharmaceutical_forms'
      get 'duration_types'
      get 'dose_frequency_types'
      get 'administration_ways'
      get 'recipe_types'
      get 'specialties'
    end
  end

  resources :states
  resources :cities
  resources :families
  resources :companies do
    collection do
      post 'change_company'
    end
  end
  resources :appointment_demands
  resources :appointment_bookings
  resources :family_members do
    resources :patient_records
  end
  resources :home_registrations
  resources :professional_teams
  resources :health_professionals
  resources :health_establishments
  resources :home_visit_forms
  resources :home_visit_registrations
  resources :individual_registrations
  resources :vaccinations
  resources :vaccination_campaigns do
    member do
      get 'update_map'
    end
  end
  resources :roles
  resources :sms_messages
  resources :sms_schedules do
    member do
      post 'send_sms_messages'
    end
  end
  resources :medicines
  resources :vaccines
  resources :periods
  resources :period_items, only: %i[index show]
  resources :reports, only: [] do
    collection do
      get 'vaccinations'
      get 'home_registrations'
      get 'home_visit_registrations'
      get 'families'
      get 'family_members'
      get 'vaccination_campaigns'
      get 'individual_registrations'
      get 'resume_registry'
      get 'sociodemographic_situation'
      get 'street_situation'
      get 'family_member_disabilities'
    end
  end

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
  }, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }

  devise_scope :user do
    resources :users
  end

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth', controllers: {
      sessions: 'api/overrides/sessions',
    }

    resources :states
    resources :cities
    resources :families
    resources :family_members

    # Home Registrations
    resources :home_registrations, except: %i[new edit]
    resources :living_conditions, except: %i[index new edit]
    resources :addresses, except: %i[index new edit]

    # Professional Teams
    resources :professional_teams, except: %i[new edit] do
      shallow do
        resources :health_professionals, except: %i[new edit] do
          shallow do
            resources :home_registrations, only: %i[index]
          end
        end
      end
    end

    # Home Visit Registrations
    resources :home_visit_registrations
    resources :home_visit_forms

    # States & Cities
    resources :states, only: %i[index show] do
      shallow do
        resources :cities, only: %i[index show]
      end
    end

    # Individual Registrations
    resources :individual_registrations, except: %i[new edit]
    resources :health_conditions, except: %i[index new edit]
    resources :living_conditions, except: %i[index new edit]
    resources :in_street_situations, except: %i[index new edit]
    resources :sociodemographic_infos, except: %i[index new edit]
    resources :cancel_registrations, except: %i[index new edit]

    # Health Establishments
    resources :health_establishments, except: %i[index new edit] do
      shallow do
        resources :health_professionals, only: %i[index show]
      end
    end

    # Generic Models
    resources :generic_models, only: :types do
     collection do
       get 'types'
     end
    end
  end
end

app/models/company.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: companies
#
#  id               :bigint           not null, primary key
#  complement       :string
#  district         :string
#  fancy_name       :string
#  federal_registry :string
#  legal_full_name  :string
#  number           :string
#  patio            :string
#  reference        :string
#  slug             :string
#  state_registry   :string
#  zip              :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  city_id          :bigint
#
# Indexes
#
#  index_companies_on_city_id  (city_id)
#
# Foreign Keys
#
#  fk_rails_...  (city_id => cities.id)
#

class Company < ApplicationRecord
  include Sluggable

  belongs_to :city, optional: true

  has_many :user_companies, dependent: :destroy
  has_many :users, through: :user_companies

  validates :legal_full_name, presence: true

  ransack_alias :search, :id_to_s_or_legal_full_name_or_fancy_name_or_federal_registry_or_state_registry

  def name_formatted
    "#{federal_registry} - #{legal_full_name}"
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < WebController
  before_action :set_company, only: %i[show edit update destroy]

  # GET /companies
  def index
    @query = Company.ransack(params[:q])
    @pagy, @companies = pagy(@query.result.includes(:city)
                               .order(id: :desc), page: params[:page], items: 10)
  end

  # GET /companies/1
  def show; end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit; end

  # POST /companies
  def create
    @company = Company.new(company_params)
    @city_selected = @company.city.presence
    if @company.save
      redirect_to(companies_url, notice: 'Company was successfully created.')
    else
      render(:new)
    end
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to(companies_url, notice: 'Company was successfully updated.')
    else
      render(:edit)
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    redirect_to(companies_url, notice: 'Company was successfully destroyed.')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.friendly.find(params[:id])
    @city_selected = @company.city.presence
  end

  # Only allow a trusted parameter "white list" through.
  def company_params
    params.require(:company).permit(:legal_full_name, :fancy_name,
                                    :federal_registry, :state_registry,
                                    :patio, :number, :zip, :reference,
                                    :district, :city_id, :complement)
  end
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <% content_for :body do %>
    <%= f.input :legal_full_name, wrapper_html: {class: 'col-lg-6 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.input :fancy_name, wrapper_html: {class: 'col-lg-6 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.input :federal_registry, wrapper_html: {class: 'col-lg-3 col-sm-12'},
                input_html: {class: 'federal-registry', disabled: show?(f.object.persisted?)} %>
    <%= f.input :state_registry, wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.input :patio, wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.input :number, wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.input :zip, wrapper: :horizontal_input_group, wrapper_html: {class: 'col-lg-3 col-sm-12'} do %>
      <%= f.input_field :zip, label_text: 'text', class: 'zip form-control', disabled: show?(f.object.persisted?) %>
      <div class="input-group-append">
        <button class="btn btn-icon btn-primary btn-zip px-3" type="button">
          <i class="fas fa-search"></i>
        </button>
      </div>
    <% end %>
    <%= f.input :reference, wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.input :district, wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.association :city,
                      collection: @city_selected ? [@city_selected] : [],
                      selected: @city_selected,
                      label_method: :name_formatted,
                      wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {class: 'cities', disabled: show?(f.object.persisted?)} %>
    <%= f.input :complement, wrapper_html: {class: 'col-lg-6 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
  <% end %>
  <%= render template: 'application/form', locals: {form: @company} %>
<% end %>

app/views/companies/edit.html.erb
<%= render 'form', form: @company %>

app/views/companies/index.html.erb
<%= render 'application/page_header', model: Company %>
<div class="card">
  <div class="card-status bg-transparent"></div>
  <div class="card-header p-4">
    <div class="col-sm-12 col-lg-12">
      <div class="form-row">
        <div class="col-sm-12 col-lg-6 p-0">
          <%= render 'application/pagy_count', list: @pagy, model: Company, url: new_company_path %>
        </div>
        <div class="col-sm-12 col-lg-6 p-0">
          <%= search_form_for @query do |f| %>
            <%= f.search_field :search_cont, class: 'form-control', placeholder: t('helpers.search') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body table-responsive p-0 m-0">
    <table class="table card-table table-vcenter text-nowrap table-hover">
      <thead>
      <tr>
        <th>#</th>
        <th><%= Company.human_attribute_name :legal_full_name %></th>
        <th><%= Company.human_attribute_name :fancy_name %></th>
        <th><%= Company.human_attribute_name :federal_registry %></th>
        <th><%= Company.human_attribute_name :state_registry %></th>
        <th><%= Company.human_attribute_name :city %></th>
        <th><%= City.human_attribute_name :state %></th>
        <th><%= t('helpers.actions.action') %></th>
      </tr>
      </thead>
      <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td class="text-muted">
            <%= company.id.to_s.rjust 8, '0' %>
          </td>
          <td><%= company.legal_full_name %></td>
          <td><%= company.fancy_name %></td>
          <td><%= company.federal_registry %></td>
          <td><%= company.state_registry %></td>
          <td><%= company&.city&.name %></td>
          <td><%= company&.city&.state&.name_formatted %></td>
          <td class="text-center">
            <%= render 'application/table_links', f: company %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <%= render 'application/footer_links', url: new_company_path, model: Company %>
  </div>
</div>

app/views/companies/new.html.erb
<%= render 'form', form: @company %>

app/views/companies/show.html.erb
<%= render 'form', form: @company %>