config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get '/check', to: proc {[200, {}, ['it_works']]}
  # Sidekiq web config
  scope :monitoring do
    mount Sidekiq::Web => '/sidekiq'
    Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
      [user, password] == [ENV['SIDEKIQ_USERNAME'], ENV['SIDEKIQ_PASSWORD']]
    end
    Sidekiq::Web.set(:session_secret, Rails.application.secrets[:secret_key_base])
  end

  get 'dashboard', to: 'dashboards#dashboard'
  root to: 'dashboards#dashboard'

  # Dashboard charts
  resources :charts do
    collection do
      get 'chart_families'
      get 'chart_family_members'
      get 'chart_home_visit_registrations'
      get 'chart_home_registrations'
      get 'chart_individual_registrations'
      get 'chart_periods'
      get 'chart_vaccinations'
    end
  end

  resources :generic_models do
    collection do
      get 'address_types'
      get 'cbo_types'
      get 'ethnicity_types'
      get 'carried_procedures'
      get 'exams'
      get 'pharmaceutical_forms'
      get 'duration_types'
      get 'dose_frequency_types'
      get 'administration_ways'
      get 'recipe_types'
      get 'specialties'
    end
  end

  resources :states
  resources :cities
  resources :families
  resources :companies do
    collection do
      post 'change_company'
    end
  end
  resources :appointment_demands
  resources :appointment_bookings
  resources :family_members do
    resources :patient_records
  end
  resources :home_registrations
  resources :professional_teams
  resources :health_professionals
  resources :health_establishments
  resources :home_visit_forms
  resources :home_visit_registrations
  resources :individual_registrations
  resources :vaccinations
  resources :vaccination_campaigns do
    member do
      get 'update_map'
    end
  end
  resources :roles
  resources :sms_messages
  resources :sms_schedules do
    member do
      post 'send_sms_messages'
    end
  end
  resources :medicines
  resources :vaccines
  resources :periods
  resources :period_items, only: %i[index show]
  resources :reports, only: [] do
    collection do
      get 'vaccinations'
      get 'home_registrations'
      get 'home_visit_registrations'
      get 'families'
      get 'family_members'
      get 'vaccination_campaigns'
      get 'individual_registrations'
      get 'resume_registry'
      get 'sociodemographic_situation'
      get 'street_situation'
      get 'family_member_disabilities'
    end
  end

  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
  }, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }

  devise_scope :user do
    resources :users
  end

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth', controllers: {
      sessions: 'api/overrides/sessions',
    }

    resources :states
    resources :cities
    resources :families
    resources :family_members

    # Home Registrations
    resources :home_registrations, except: %i[new edit]
    resources :living_conditions, except: %i[index new edit]
    resources :addresses, except: %i[index new edit]

    # Professional Teams
    resources :professional_teams, except: %i[new edit] do
      shallow do
        resources :health_professionals, except: %i[new edit] do
          shallow do
            resources :home_registrations, only: %i[index]
          end
        end
      end
    end

    # Home Visit Registrations
    resources :home_visit_registrations
    resources :home_visit_forms

    # States & Cities
    resources :states, only: %i[index show] do
      shallow do
        resources :cities, only: %i[index show]
      end
    end

    # Individual Registrations
    resources :individual_registrations, except: %i[new edit]
    resources :health_conditions, except: %i[index new edit]
    resources :living_conditions, except: %i[index new edit]
    resources :in_street_situations, except: %i[index new edit]
    resources :sociodemographic_infos, except: %i[index new edit]
    resources :cancel_registrations, except: %i[index new edit]

    # Health Establishments
    resources :health_establishments, except: %i[index new edit] do
      shallow do
        resources :health_professionals, only: %i[index show]
      end
    end

    # Generic Models
    resources :generic_models, only: :types do
     collection do
       get 'types'
     end
    end
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < WebController
  breadcrumb 'Relatórios', :root_path

  def families
    authorize(:report, :families?)
    @query = Family.ransack(permitted_params)
    @result = @query.result.includes(:family_income)
    @result = @result.where(user: current_user) if current_user.agent?
    if @result.empty?
      blank_return
    else
      query_return(@result, @result.includes(family_members: [:ethnicity, :gender, :home_registration, :race,
                                                              :birth_country, :nationality, :company, city: [:state]]).map(&:family_members).flatten)
    end
  end

  def family_members
    authorize(:report, :family_members?)
    @query = FamilyMember.ransack(permitted_params)
    @result = @query.result
    @result = @result.where(user: current_user) if current_user.agent?
    if @result.empty?
      blank_return
    else
      @result = @result.includes(:ethnicity, :gender, :home_registration, :race,
                                 :birth_country, :nationality, :company, city: [:state])
      query_return(@result, @result)
    end
  end

  def individual_registrations
    authorize(:report, :individual_registrations?)
    @query = IndividualRegistration.ransack(permitted_params)
    @result = @query.result
    @result = @result.where(user: current_user) if current_user.agent?
    if @result.empty?
      blank_return
    else
      @result = @result.includes(sociodemographic_info:
                                     %i[gender_identity parent_relation occupation job_market_situation],
                                 family_member: %i[ethnicity gender home_registration])
      query_return(@result, @result.map(&:family_member).flatten)
    end
  end

  def home_registrations
    authorize(:report, :home_registrations?)
    @query = HomeRegistration.ransack(permitted_params)
    @result = @query.result
    @result = @result.where(user: current_user) if current_user.agent?
    if @result.empty?
      blank_return
    else
      @result = @result.includes(family_members: %i[ethnicity gender home_registration])
      query_return(@result, @result.map(&:family_members).flatten)
    end
  end

  def home_visit_registrations
    authorize(:report, :home_visit_registrations?)
    @query = HomeVisitForm.ransack(permitted_params)
    @result = @query.result
    @result = @result.includes(:user).where(user: current_user)
    if @result.empty?
      blank_return
    else
      @result = @result.includes(family_members: %i[ethnicity gender home_registration])
      query_return(@result, @result.map(&:family_member).flatten)
    end
  end

  def vaccinations
    authorize(:report, :vaccinations?)
    @query = Vaccination.ransack(permitted_params)
    @result = @query.result
    @result = @result.where(user: current_user) if current_user.agent?
    if @result.empty?
      blank_return
    else
      @result = @result.includes(family_member: %i[ethnicity gender home_registration])
      query_return(@result, @result.map(&:family_member).flatten)
    end
  end

  def resume_registry
    authorize(:report, :resume_registry?)
    @family_members = FamilyMember.where(created_at: params[:start_date]..params[:end_date]).count
  end

  def sociodemographic_situation
    authorize(:report, :sociodemographic_situation?)
  end

  def street_situation
    authorize(:report, :street_situation?)
  end

  def family_member_disabilities
    authorize(:report, :family_member_disabilities?)
  end

  private

  def permitted_params
    return if params[:q].blank?

    params[:q].delete_if { |_query, value| value.blank? || value == false }
  end

  def blank_return
    respond_to do |format|
      format.html do
        @pagy, @list = pagy(@result, page: params[:page], items: 10)
      end
      format.json do
        render_json []
      end
    end
  end

  def query_return(result, family_members)
    respond_to do |format|
      format.html do
        @pagy, @list = pagy(result, page: params[:page], items: 10)
      end
      format.json do
        render_json family_members
      end
    end
  end
end

app/views/reports/families.html.erb
<div class="row">
  <%= search_form_for @query, url: families_reports_path do |f| %>
    <div class="modal fade" id="search-form-modal"
         tabindex="-1" role="dialog" aria-labelledby="modal-label" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title" id="modal-label">
              Filtro de <%= Family.model_name.human(count: 2) %>
            </h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true"></span>
            </button>
          </div>
          <div class="modal-body">
            <div class="card-body p-2 o-auto" style="height: 35rem;">
              <%= f.input :responsible_cns_number_eq, label: "#{Family.human_attribute_name :responsible_cns_number}", required: false, wrapper_html: {class: 'col-lg-12 col-sm-12'} %>
              <%= f.input :handbook_number_eq, label: "#{Family.human_attribute_name :handbook_number}", required: false, wrapper_html: {class: 'col-lg-12 col-sm-12'} %>
              <div class="col-lg-12">
                <div class="row">
                  <%= f.input :members_quantity_gteq, required: false, label: "#{Family.human_attribute_name :members_quantity} de",
                              as: :integer, wrapper_html: {class: 'col-lg-6 col-sm-12'} %>
                  <%= f.input :members_quantity_lteq, required: false, label: "até",
                              as: :integer, wrapper_html: {class: 'col-lg-6 col-sm-12'} %>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="row">
                  <%= f.input :reside_since_gteq, required: false, label: "#{Family.human_attribute_name :reside_since} de",
                              as: :date, html5: true, wrapper_html: {class: 'col-lg-6 col-sm-12'} %>
                  <%= f.input :reside_since_gteq, required: false, label: "até",
                              as: :date, html5: true, wrapper_html: {class: 'col-lg-6 col-sm-12'} %>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="form-group">
                  <label class="form-label"><%= Family.human_attribute_name :family_income %> em</label>
                  <%= select_tag :family_income_id_in,
                                 options_from_collection_for_select(GenericModel.family_incomes,
                                                                    :id, :name_formatted, params[:family_income_id_in]),
                                 {include_blank: true, multiple: true, class: 'select2-multiple form-control'} %>
                </div>
              </div>
              <%= f.input :moving_true, as: :boolean, required: false, wrapper_html: {class: 'col-lg-6 col-sm-12 pl-3 mb-3'} %>
            </div>
          </div>
          <div class="modal-footer">
            <%= link_to families_reports_path, class: 'btn btn-block btn-sm-block btn-danger' do %>
              <i class="fas fa-redo-alt mr-2"></i><span class="btn-title"><%= t("helpers.actions.clear") %></span>
            <% end %>
            <%= button_tag class: 'btn btn-block btn-sm-block btn-primary',
                           data: {disable_with: '<i class="fas fa-spinner fa-spin"></i>Pesquisando...'.html_safe} do %>
              <i class="fas fa-search mr-2"></i><span class="btn-title"><%= t("helpers.actions.search") %></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg-12">
        <% content_for :table_header do %>
          <thead>
          <tr>
            <th><%= Family.human_attribute_name :responsible_cns_number %></th>
            <th><%= Family.human_attribute_name :responsible_name %></th>
            <th><%= Family.human_attribute_name :handbook_number %></th>
            <th><%= Family.human_attribute_name :members_quantity %></th>
            <th><%= Family.human_attribute_name :reside_since %></th>
            <th><%= Family.human_attribute_name :family_income %></th>
            <th><%= Family.human_attribute_name :moving %></th>
          </tr>
          </thead>
        <% end %>
        <% content_for :table_body do %>
          <tbody>
          <% @list.each do |family| %>
            <tr>
              <td><%= family.responsible_cns_number %></td>
              <td><%= family.family_members&.responsible&.find_by(cns_number: family.responsible_cns_number)&.name %></td>
              <td><%= family.handbook_number %></td>
              <td><%= family.members_quantity %></td>
              <td><%= family.reside_since.strftime('%d/%m/%Y') %></td>
              <td><%= family.family_income.name_formatted %></td>
              <td><%= family.moving ? 'SIM' : 'NÃO' %></td>
            </tr>
          <% end %>
          </tbody>
        <% end %>
        <%= render template: 'reports/table', locals: {model: Family} %>
      </div>
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header p-4">
            <h3 class="mb-0">
              <i class="fas fa-map mr-2"></i>Mapa de Localização
            </h3>
          </div>
          <div id="family_map" class="card-body p-0">
            <%= render 'application/map' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/family_members.html.erb
<div class="row">
  <%= search_form_for @query, url: family_members_reports_path do |f| %>
    <div class="modal fade" id="search-form-modal"
         tabindex="-1" role="dialog" aria-labelledby="modal-label" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title" id="modal-label">
              Filtro de <%= FamilyMember.model_name.human(count: 2) %>
            </h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true"></span>
            </button>
          </div>
          <div class="modal-body">
            <div class="card-body p-2 o-auto" style="height: 35rem;">
              <div class="col-lg-12">
                <div class="row">
                  <%= f.input :birth_date_gteq, required: false, label: "#{FamilyMember.human_attribute_name :birth_date} de",
                              as: :date, html5: true, wrapper_html: {class: 'col-lg-6 col-sm-12'} %>
                  <%= f.input :birth_date_lteq, label: 'até', required: false,
                              as: :date, html5: true, wrapper_html: {class: 'btn-remove col-lg-6 col-sm-12'} %>
                </div>
              </div>
              <%= f.input :cns_number_eq, label: "#{FamilyMember.human_attribute_name :cns_number}", required: false, wrapper_html: {class: 'col-lg-12 col-sm-12'} %>
              <%= f.input :family_handbook_number_eq, label: "#{Family.human_attribute_name :handbook_number}",
                          required: false, wrapper_html: {class: 'col-lg-12 col-sm-12'} %>
              <div class="col-lg-12">
                <div class="form-group">
                  <label class="form-label"><%= FamilyMember.human_attribute_name :race %></label>
                  <%= select_tag :race_id_in,
                                 options_from_collection_for_select(GenericModel.races,
                                                                    :id, :name_formatted, params[:race_id_in]),
                                 {include_blank: true, multiple: true, class: 'select2-multiple form-control'} %>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="form-group">
                  <label class="form-label"><%= FamilyMember.human_attribute_name :gender %></label>
                  <%= select_tag :gender_id_in,
                                 options_from_collection_for_select(GenericModel.genders,
                                                                    :id, :name_formatted, params[:gender_id_in]),
                                 {include_blank: true, multiple: true, class: 'select2-multiple form-control'} %>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="form-group">
                  <label class="form-label"><%= FamilyMember.human_attribute_name :ethnicity %></label>
                  <%= select_tag :ethnicity_id_in,
                                 options_from_collection_for_select(GenericModel.ethnicities,
                                                                    :id, :name_formatted, params[:ethnicity_id_in]),
                                 {include_blank: true, multiple: true, class: 'select2-multiple form-control'} %>
                </div>
              </div>
              <%= f.input :family_family_income_id_in, label: "#{Family.human_attribute_name :family_income}", as: :select, collection: GenericModel.family_incomes, required: false,
                          wrapper_html: {class: 'col-lg-12 col-sm-12'}, input_html: {class: 'select2-multiple', multiple: true} %>
              <%= f.input :out_area_true, as: :boolean, required: false, wrapper_html: {class: 'col-lg-6 col-sm-12 pl-3 mb-3'} %>
            </div>
          </div>
          <div class="modal-footer">
            <%= link_to family_members_reports_path, class: 'btn btn-block btn-sm-block btn-danger' do %>
              <i class="fas fa-redo-alt mr-2"></i><span class="btn-title"><%= t("helpers.actions.clear") %></span>
            <% end %>
            <%= button_tag class: 'btn btn-block btn-sm-block btn-primary',
                           data: {disable_with: '<i class="fas fa-spinner fa-spin"></i>Pesquisando...'.html_safe} do %>
              <i class="fas fa-search mr-2"></i><span class="btn-title"><%= t("helpers.actions.search") %></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg-12">
        <% content_for :table_header do %>
          <thead>
          <tr>
            <th><%= FamilyMember.human_attribute_name :name %></th>
            <th><%= FamilyMember.human_attribute_name :cns_number %></th>
            <th><%= FamilyMember.human_attribute_name :birth_date %></th>
            <th><%= FamilyMember.human_attribute_name :age %></th>
            <th><%= FamilyMember.human_attribute_name :city %></th>
            <th><%= Address.human_attribute_name :district %></th>
            <th><%= FamilyMember.human_attribute_name :gender %></th>
            <th><%= FamilyMember.human_attribute_name :family %></th>
          </tr>
          </thead>
        <% end %>
        <% content_for :table_body do %>
          <tbody>
          <% @list.each do |family_member| %>
            <tr>
              <td><%= family_member.name %></td>
              <td><%= family_member.cns_number %></td>
              <td><%= family_member.birth_date.strftime('%d/%m/%Y') %></td>
              <% if family_member.birth_date.year == Time.current.year %>
                <td><%= distance_of_time_in_words(family_member.birth_date, Time.current.to_date, only: :months).upcase %></td>
              <% else %>
                <td><%= distance_of_time_in_words(family_member.birth_date, Time.current.to_date, only: :years).upcase %></td>
              <% end %>
              <td><%= family_member.city.name_formatted %></td>
              <td><%= family_member&.home_registration&.address&.district %></td>
              <td><%= family_member.gender.name %></td>
              <td><%= family_member&.family&.handbook_number %></td>
            </tr>
          <% end %>
          </tbody>
        <% end %>
        <%= render template: 'reports/table', locals: {model: FamilyMember} %>
      </div>
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header p-4">
            <h3 class="mb-0">
              <i class="fas fa-map mr-2"></i>Mapa de Localização
            </h3>
          </div>
          <div id="family_member_map" class="card-body p-0">
            <%= render 'application/map' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/home_registrations.html.erb
<div class="row">
  <%= search_form_for @query, url: home_registrations_reports_path do |f| %>
    <div class="modal fade" id="search-form-modal"
         tabindex="-1" role="dialog" aria-labelledby="modal-label" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title" id="modal-label">
              Filtro de <%= HomeRegistration.model_name.human(count: 2)[10..-1][0..19] %>
            </h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true"></span>
            </button>
          </div>
          <div class="modal-body">
            <div class="card-body p-2 o-auto" style="height: 35rem;">
              <%= f.input :health_professional_id_eq, required: false, wrapper_html: {class: 'col-lg-12 col-sm-12'} %>
              <%= f.input :living_condition_rooms_eq, required: false, wrapper_html: {class: 'col-lg-12 col-sm-12'} %>
              <div class="col-lg-12">
                <div class="row">
                  <%= f.input :pet_quantity_gteq, as: :integer, required: false, label: "#{HomeRegistration.human_attribute_name :pet_quantity} de", wrapper_html: {class: 'col-lg-6 col-sm-12'} %>
                  <%= f.input :pet_quantity_lteq, as: :integer, label: 'até', required: false, wrapper_html: {class: 'col-lg-6 col-sm-12'} %>
                </div>
              </div>
              <%= f.input :home_type_id_in, as: :select, collection: GenericModel.residence_types, required: false,
                          wrapper_html: {class: 'col-lg-12 col-sm-12'}, input_html: {class: 'select2-multiple', multiple: true} %>
              <div class="col-lg-12">
                <div class="row">
                  <%= f.input :living_condition_residents_gteq, as: :integer, required: false, label: "#{LivingCondition.human_attribute_name :residents} de", wrapper_html: {class: 'col-lg-6 col-sm-12'} %>
                  <%= f.input :living_condition_residents_lteq, as: :integer, label: 'até', required: false, wrapper_html: {class: 'col-lg-6 col-sm-12'} %>
                </div>
              </div>
              <%= f.input :living_condition_water_supply_id_in, as: :select, collection: GenericModel.water_supplies, required: false,
                          wrapper_html: {class: 'col-lg-12 col-sm-12'}, input_html: {class: 'select2-multiple', multiple: true} %>
              <%= f.input :living_condition_garbage_disposal_id_in, as: :select, collection: GenericModel.garbage_disposals, required: false,
                          wrapper_html: {class: 'col-lg-12 col-sm-12'}, input_html: {class: 'select2-multiple', multiple: true} %>
              <%= f.input :living_condition_bathroom_drainage_id_in, as: :select, collection: GenericModel.bathroom_drainage, required: false,
                          wrapper_html: {class: 'col-lg-12 col-sm-12'}, input_html: {class: 'select2-multiple', multiple: true} %>
              <%= f.input :living_condition_home_location_id_in, as: :select, collection: GenericModel.home_locations, required: false,
                          wrapper_html: {class: 'col-lg-12 col-sm-12'}, input_html: {class: 'select2-multiple', multiple: true} %>
              <%= f.input :living_condition_home_situation_id_in, as: :select, collection: GenericModel.home_situations, required: false,
                          wrapper_html: {class: 'col-lg-12 col-sm-12'}, input_html: {class: 'select2-multiple', multiple: true} %>
              <%= f.input :living_condition_home_wall_material_id_in, as: :select, collection: GenericModel.home_wall_materials, required: false,
                          wrapper_html: {class: 'col-lg-12 col-sm-12'}, input_html: {class: 'select2-multiple', multiple: true} %>
              <%= f.input :living_condition_home_type_id_in, as: :select, collection: GenericModel.home_types, required: false,
                          wrapper_html: {class: 'col-lg-12 col-sm-12'}, input_html: {class: 'select2-multiple', multiple: true} %>
              <%= f.input :living_condition_water_treatment_id_in, as: :select, collection: GenericModel.water_treatments, required: false,
                          wrapper_html: {class: 'col-lg-12 col-sm-12'}, input_html: {class: 'select2-multiple', multiple: true} %>
              <%= f.input :living_condition_electric_power_true, as: :boolean, required: false, wrapper_html: {class: 'col-lg-12 col-sm-12 pl-3 mb-3'} %>
              <%= f.input :refuse_registration_true, as: :boolean, required: false, wrapper_html: {class: 'col-lg-12 col-sm-12 pl-3 mb-3'} %>
            </div>
          </div>
          <div class="modal-footer">
            <%= link_to home_registrations_reports_path, class: 'btn btn-block btn-sm-block btn-danger' do %>
              <i class="fas fa-redo-alt mr-2"></i><span class="btn-title"><%= t("helpers.actions.clear") %></span>
            <% end %>
            <%= button_tag class: 'btn btn-block btn-sm-block btn-primary',
                           data: {disable_with: '<i class="fas fa-spinner fa-spin"></i>Pesquisando...'.html_safe} do %>
              <i class="fas fa-search mr-2"></i><span class="btn-title"><%= t("helpers.actions.search") %></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg-12">
        <% content_for :table_header do %>
          <thead>
          <tr>
            <th><%= HomeRegistration.human_attribute_name :health_professional %></th>
            <th><%= HomeRegistration.human_attribute_name :pet_quantity %></th>
            <th><%= HomeRegistration.human_attribute_name :refuse_registration %></th>
            <th><%= LivingCondition.human_attribute_name :water_supply %></th>
            <th><%= LivingCondition.human_attribute_name :rural_production_area %></th>
            <th><%= LivingCondition.human_attribute_name :garbage_disposal %></th>
            <th><%= LivingCondition.human_attribute_name :bathroom_drainage %></th>
            <th><%= LivingCondition.human_attribute_name :home_location %></th>
          </tr>
          </thead>
        <% end %>
        <% content_for :table_body do %>
          <tbody>
          <% @list.each do |home_registration| %>
            <tr>
              <td><%= home_registration.health_professional.full_name %></td>
              <td><%= home_registration.pet_quantity %></td>
              <td><%= home_registration.refuse_registration ? 'SIM' : 'NÃO' %></td>
              <td><%= home_registration.living_condition&.water_supply&.name_formatted %></td>
              <td><%= home_registration.living_condition&.rural_production_area&.name_formatted %></td>
              <td><%= home_registration.living_condition&.garbage_disposal&.name_formatted %></td>
              <td><%= home_registration.living_condition&.bathroom_drainage&.name_formatted %></td>
              <td><%= home_registration.living_condition&.home_location&.name_formatted %></td>
            </tr>
          <% end %>
          </tbody>
        <% end %>
        <%= render template: 'reports/table', locals: {model: HomeRegistration} %>
      </div>
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header p-4">
            <h3 class="mb-0">
              <i class="fas fa-map mr-2"></i>Mapa de Localização
            </h3>
          </div>
          <div id="home_registration_map" class="card-body p-0">
            <%= render 'application/map' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/resume_registry.html.erb
<div class="row mt-5">
  <div class="col-lg-12">
    <%= form_for synthetic_reports_reports_path do |f| %>
      <div class="card">
        <div class="card-header p-4">
          <h3 class="mb-0">
            <i class="fas fa-map mr-2"></i>Relatórios de Cadastro do Território
          </h3>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">
              <div class="form-group">
                <label class="form-label"><%= t('activerecord.attributes.period.report') %></label>
                <%= f.select 'start_date', ['resume_registry', 2, 3, 4, 5, 6].collect { |a| [a, a] }, {}, {name: 'synthetic_report', class: 'form-control select2', include_blank: true} %>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="form-group">
                <label class="form-label"><%= t('activerecord.attributes.period.start_date') %></label>
                <%= f.text_field 'start_date', type: 'date', name: 'start_date', class: 'form-control' %>
              </div>
            </div>
            <div class="col-lg-3">
              <div class="form-group">
                <label class="form-label"><%= t('activerecord.attributes.period.end_date') %></label>
                <%= f.text_field 'end_date', type: 'date', name: 'end_date', class: 'form-control' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>